#!/usr/bin/env python3
"""Generates std/unicode_tables.h from the Unicode Character Database.

Usage: scripts/gen-unicode-tables.py UCD_DIR
UCD_DIR must contain GraphemeBreakProperty.txt, emoji-data.txt and
DerivedCoreProperties.txt from https://www.unicode.org/Public/<version>/ucd/
(the first and second live in auxiliary/ and emoji/ there).
"""
import os
import re
import sys

GCB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend",
       "SpacingMark", "L", "V", "T", "LV", "LVT"]
INCB = ["None", "Consonant", "Extend", "Linker"]


def ranges(path, select):
    """(lo, hi, value) for each line whose fields select() maps to a value."""
    out = []
    for line in open(path, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        value = select(fields)
        if value is None:
            continue
        lo, _, hi = fields[0].partition("..")
        out.append((int(lo, 16), int(hi or lo, 16), value))
    out.sort()
    merged = []
    for lo, hi, value in out:
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == lo:
            merged[-1] = (merged[-1][0], hi, value)
        else:
            merged.append((lo, hi, value))
    return merged


def version(path):
    match = re.search(r"-(\d+\.\d+\.\d+)\.txt", open(path, encoding="utf-8").readline())
    return match.group(1) if match else "unknown"


def table(name, rows, with_value):
    lines = [f"static const RlUnicodeRange {name}[] = {{"]
    for lo, hi, value in rows:
        lines.append(f"    {{0x{lo:04X}, 0x{hi:04X}, {value if with_value else 1}}},")
    lines.append("};")
    return "\n".join(lines)


def main():
    ucd = sys.argv[1]
    gcb_path = os.path.join(ucd, "GraphemeBreakProperty.txt")
    gcb = ranges(gcb_path, lambda f: GCB.index(f[1]))
    pict = ranges(os.path.join(ucd, "emoji-data.txt"), lambda f: 1 if f[1] == "Extended_Pictographic" else None)
    incb = ranges(os.path.join(ucd, "DerivedCoreProperties.txt"),
                  lambda f: INCB.index(f[2]) if len(f) > 2 and f[1] == "InCB" else None)
    header = f"""// Generated by scripts/gen-unicode-tables.py from Unicode {version(gcb_path)} data. Do not edit.
#ifndef ROLANG_STD_UNICODE_TABLES_H
#define ROLANG_STD_UNICODE_TABLES_H

#include <stdint.h>

typedef struct {{ uint32_t lo; uint32_t hi; uint8_t value; }} RlUnicodeRange;

enum {{ {", ".join(f"RL_GCB_{v.upper()} = {i}" for i, v in enumerate(GCB))} }};
enum {{ {", ".join(f"RL_INCB_{v.upper()} = {i}" for i, v in enumerate(INCB))} }};

{table("rl_grapheme_break", gcb, True)}

{table("rl_extended_pictographic", pict, False)}

{table("rl_indic_conjunct_break", incb, True)}

#endif /* ROLANG_STD_UNICODE_TABLES_H */
"""
    sys.stdout.write(header)


main()
